- name: Install PHP and Apache
  ansible.builtin.apt:
    name:
      - apache2
      - ghostscript
      - libapache2-mod-php 
      - mysql-server 
      - php 
      - php-bcmath 
      - php-curl 
      - php-imagick 
      - php-intl 
      - php-json 
      - php-mbstring 
      - php-mysql 
      - php-xml 
      - php-zip
    state: present
    update_cache: yes

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
